version: '3.8'

services:
  simulator:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "11311:11311" # ROS master port
    volumes:
      - .:/root/fira/src/FIRA-Air-Simulator # Mount the project directory for development
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority
    environment:
      - ROS_MASTER_URI=http://localhost:11311
      - ROS_HOSTNAME=localhost
      - DISPLAY=$DISPLAY    
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=graphics,utility,compute
      - QT_X11_NO_MITSHM=1
      - LIBGL_ALWAYS_SOFTWARE=1
    command: /bin/bash -c "source /root/fira/devel/setup.bash && roslaunch fira_challenge_env main.launch"